AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
    #  Handler: helloworld.App::envHandler
     # Handler: helloworld.App::handleVariables
      Handler: helloworld.App::handlerWithTimeout
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      # max is 900(15 minutes)
      # default is 3 seconds
      Timeout: 2
      Environment:
        Variables:
          DATABASE_URL: my-database-url
          restapiurl: testurl
      
      

